Change (docker): Combine nginx and php to a single image for both `ASP` and `bf2sclone` with env var support for configuration
Previous: In <= v2.5.x, `asp` and `bf2sclone` each had separate `nginx` and `php` images.

Now: Single `asp` and `bf2sclone` images containing both `nginx` and `php`, with environment variable support, and entrypoint that sets the correct permissions.

Benefits:
- Easier to deploy / upgrade. No need to separate `asp-nginx` and `asp-php` containers
- Environment variable configuration means no more need to mount `config.php` into `asp` and `bf2sclone` containers
- Entrypoint script sets permissions on volumes. `init-container` should only need to set permissions for `db` volume.

Notable changes:
- Add documentation for upgrading docker images to v2.6.x from prior versions
- Update `./docs/examples`
- Add tests for production builds for examples in `./docs/examples`

Closes #132

diff --git a/.github/workflows/ci-master-pr.yml b/.github/workflows/ci-master-pr.yml
--- a/.github/workflows/ci-master-pr.yml
+++ b/.github/workflows/ci-master-pr.yml
@@ -16,49 +16,33 @@ jobs:
       matrix:
         testenv:
           - dev
+          - prod
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v3
 
-    - name: Set up Docker Buildx
-      id: buildx
-      uses: docker/setup-buildx-action@v2
+    # This is commented out, so we use the default 'docker' driver instead of the 'docker-container' driver. When using 'docker-container' driver, there appears to be a rate limit on writes on Github CI which causes buildx to fail with error code 17 when it is exporting to cache
+    # - name: Set up Docker Buildx
+    #   id: buildx
+    #   uses: docker/setup-buildx-action@v2
 
-    - name: Cache Docker layers (asp-nginx)
-      uses: actions/cache@v3
+    - name: Cache Docker layers (asp)
+      uses: actions/cache/restore@v3  # Restore cache but don't save it at end of job
       with:
-        path: /tmp/.buildx-asp-cache-nginx
-        key: ${{ runner.os }}-buildx-asp-nginx-${{ github.sha }}
+        path: /tmp/.buildx-cache-asp
+        key: ${{ runner.os }}-buildx-asp-${{ github.sha }}
         restore-keys: |
-          ${{ runner.os }}-buildx-asp-nginx-
+          ${{ runner.os }}-buildx-asp-
           ${{ runner.os }}-buildx-
 
-    - name: Cache Docker layers (asp-php)
-      uses: actions/cache@v3
+    - name: Cache Docker layers (bf2sclone)
+      uses: actions/cache/restore@v3  # Restore cache but don't save it at end of job
       with:
-        path: /tmp/.buildx-cache-asp-php
-        key: ${{ runner.os }}-buildx-asp-php-${{ github.sha }}
+        path: /tmp/.buildx-cache-bf2sclone
+        key: ${{ runner.os }}-buildx-bf2sclone-${{ github.sha }}
         restore-keys: |
-          ${{ runner.os }}-buildx-asp-php-
-          ${{ runner.os }}-buildx-
-
-    - name: Cache Docker layers (bf2sclone-nginx)
-      uses: actions/cache@v3
-      with:
-        path: /tmp/.buildx-bf2sclone-cache-nginx
-        key: ${{ runner.os }}-buildx-bf2sclone-nginx-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-buildx-bf2sclone-nginx-
-          ${{ runner.os }}-buildx-
-
-    - name: Cache Docker layers (bf2sclone-php)
-      uses: actions/cache@v3
-      with:
-        path: /tmp/.buildx-cache-bf2sclone-php
-        key: ${{ runner.os }}-buildx-bf2sclone-php-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-buildx-bf2sclone-php-
+          ${{ runner.os }}-buildx-bf2sclone-
           ${{ runner.os }}-buildx-
 
     - name: Print buildx and compose
@@ -71,17 +55,33 @@ jobs:
       if: matrix.testenv == 'dev'
       run: |
         set -eux
-        docker compose -f docker-compose.yml -f docker-compose.build.yml up --build -d
-        docker compose -f docker-compose.test.yml up
+        ./test/test.sh dev 1 1
+
+    - name: Integration test 1 (prod)
+      if: matrix.testenv == 'prod'
+      run: |
+        set -eux
+        ./test/test.sh prod1 1 1
+
+    - name: Integration test 2 (prod)
+      if: matrix.testenv == 'prod'
+      run: |
+        set -eux
+
+        # Don't publish coredns ports to prevent conflict with system-resolved on github CI
+        # sed -i '$!N;s@ports:\n      - 53:53.*@@;P;D' docker-compose.yml
+
+        # Make coredns listen on localhost only to prevent conflict with system-resolved on github CI
+        sed -i 's/- 53:53/- 127.0.0.1:53:53/' docs/full-bf2-stack-example/docker-compose.yml
+
+        ./test/test.sh prod2 1 1
 
   build:
     strategy:
       matrix:
         variant:
-          - asp-nginx
-          - asp-php
-          - bf2sclone-nginx
-          - bf2sclone-php
+          - asp
+          - bf2sclone
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
